# basic options
author: nstflecher
email: personalnst@gmail.com
description: A wonderful site
twitter_username: nstflecher
github_username: nstflecher

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
