# basic options
author: nstflecher
email: personalnst@gmail.com
description: This is my first website built with Github
twitter_username: nstflecher
github_username: nstflecher

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
